name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        options: > 
          --health-cmd="pg_isready -U ${{ secrets.DATABASE_USER }}" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for PostgreSQL
      run: |
        while ! pg_isready -h localhost -p 5432 -U ${{ secrets.DATABASE_USER }}; do
          sleep 1
        done

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY}}
        AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME}}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
      run: |
        python manage.py migrate
        python manage.py test
